### ISSUE TITLE
[BUG] The app crashes whenever I use the top right buttons

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1491]
**Reported here**:
https://www.reddit.com/r/redditsync/comments/vhk6pi
> For the last few days, If I press either the sort or the more options buttons, sync crashes immediately. The mark-everything-read button in the inbox does the same, but the search button does not.
> 
> I tried a new install, to no effect, and I'm using a Motorola g8 plus. Is there anything I can do about this?
> 
> Edit:
> 
> **Device information**
> 
>     Sync version: v22.06.17-16:57    
>     Sync flavor: free    
>     Removed ads: true    
>     
>     View type: Smaller cards    
>     Push enabled: false    
>     
>     Device: doha_n    
>     Model: motorola moto g(8) plus    
>     Android: 10

**Comment by hiciu** [comment]
I have the same issue with motorola moto g7. It crashes when I click on the 3 dots in the right upper corner. Started to happen few weeks ago. Does not matter if I'm logged in or not, clearing cache and app data did not help.

`adb logcat` says:

```
09-01 16:01:13.445  1769  3424 V WindowManager: Changing focus from Window{533d9a9 u0 com.laurencedawson.reddit_sync.pro/com.laurencedawson.reddit_sync.ui.activities.MainActivity} to Window{6884195 u0 com.laurencedawson.reddit_sync.pro/com.laurencedawson.reddit_sync.ui.activities.MainActivity} displayId=0
09-01 16:01:13.454 23636 23636 D AndroidRuntime: Shutting down VM
09-01 16:01:13.455 23636 23636 E AndroidRuntime: FATAL EXCEPTION: main
09-01 16:01:13.455 23636 23636 E AndroidRuntime: Process: com.laurencedawson.reddit_sync.pro, PID: 23636 
09-01 16:01:13.455 23636 23636 E AndroidRuntime: java.lang.IllegalArgumentException: The view is not associated with BottomSheetBehavior
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at com.google.android.material.bottomsheet.BottomSheetBehavior.g0(BottomSheetBehavior.java:7)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at com.google.android.material.bottomsheet.BottomSheetDialog$EdgeToEdgeCallback.<init>(BottomSheetDialog.java:4)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at com.google.android.material.bottomsheet.BottomSheetDialog$EdgeToEdgeCallback.<init>(BottomSheetDialog.java:1)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at com.google.android.material.bottomsheet.BottomSheetDialog$1.a(BottomSheetDialog.java:3)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at androidx.core.view.h$m$a.onApplyWindowInsets(ViewCompat.java:8)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.View.dispatchApplyWindowInsets(View.java:10550)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7194)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7206)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7196)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7206)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7196)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7206)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7196)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7206)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7196)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7206)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7196)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7206)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7196)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.ViewGroup.brokenDispatchApplyWindowInsets(ViewGroup.java:7206)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7196)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.ViewRootImpl.dispatchApplyInsets(ViewRootImpl.java:2010)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2115)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1800)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7751)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:726)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:241)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7604)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
09-01 16:01:13.455 23636 23636 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```
