### ISSUE TITLE
[BUG] Sync for reddit (Beta) crashes on launch

### ISSUE THREAD

**Issue by Sinamer** [laurencedawson/sync-for-reddit#845]
**Describe the bug**
After the splash screen of app launching, it immediately closes. I have tried reinstalling the app with no success.

**To Reproduce**
1. Launch Sync for reddit (Beta) the regular way on Android

**Smartphone:**
 - Device: POCO M3
 - OS: Android 11 (MIUI Global 12.5.7 Stable)
 - Browser: stock, Google Chrome
 - Sync Version: v22.3.21

**Additional context**
MIUI prompted to see an error report after launching the app multiple times:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.laurencedawson.reddit_sync/com.laurencedawson.reddit_sync.ui.activities.MainActivity}: android.view.InflateException: Binary XML file line #9 in com.laurencedawson.reddit_sync:layout/activity_main_drawer: Binary XML file line #20 in com.laurencedawson.reddit_sync:layout/activity_casual: Error inflating class com.laurencedawson.reddit_sync.ui.views.main.SyncBottomNavigationView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3536)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3708)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2143)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8087)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: android.view.InflateException: Binary XML file line #9 in com.laurencedawson.reddit_sync:layout/activity_main_drawer: Binary XML file line #20 in com.laurencedawson.reddit_sync:layout/activity_casual: Error inflating class com.laurencedawson.reddit_sync.ui.views.main.SyncBottomNavigationView
Caused by: android.view.InflateException: Binary XML file line #20 in com.laurencedawson.reddit_sync:layout/activity_casual: Error inflating class com.laurencedawson.reddit_sync.ui.views.main.SyncBottomNavigationView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:856)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:963)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1125)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1128)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1265)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:684)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at androidx.appcompat.app.AppCompatDelegateImpl.A(AppCompatDelegateImpl.java:23)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:1)
	at com.laurencedawson.reddit_sync.ui.activities.MainActivity.h0(MainActivity.java:60)
	at com.laurencedawson.reddit_sync.ui.activities.BaseActivity.onCreate(BaseActivity.java:38)
	at com.laurencedawson.reddit_sync.ui.activities.BaseMaterialActivity.onCreate(BaseMaterialActivity.java:0)
	at com.laurencedawson.reddit_sync.ui.activities.MainActivity.onCreate(MainActivity.java:0)
	at android.app.Activity.performCreate(Activity.java:8157)
	at android.app.Activity.performCreate(Activity.java:8129)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3509)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3708)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2143)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8087)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.IllegalArgumentException: Maximum number of items supported by SyncBottomNavigationView is 5. Limit can be checked with SyncBottomNavigationView#getMaxItemCount()
	at com.google.android.material.navigation.NavigationBarMenu.a(NavigationBarMenu.java:79)
	at androidx.appcompat.view.menu.e.add(MenuBuilder.java:3)
	at k.g$b.a(SupportMenuInflater.java:13)
	at k.g.c(SupportMenuInflater.java:130)
	at k.g.inflate(SupportMenuInflater.java:25)
	at com.google.android.material.navigation.NavigationBarView.n(NavigationBarView.java:12)
	at com.laurencedawson.reddit_sync.ui.views.main.SyncBottomNavigationView.n(SyncBottomNavigationView.java:0)
	at com.laurencedawson.reddit_sync.ui.views.main.SyncBottomNavigationView.<init>(SyncBottomNavigationView.java:21)
	... 36 more

**Comment by omair94** [comment]
occurs on Samsung Tab S8+ as well. 

Clean install (Wiped Data and Cache) has the same issue,

**Comment by justinkruit** [comment]
Seems to be mostly when using the free version, most people say they bought the IAP to remove the ads.
